server:
    port: 9000
    

database:
    type: postgres
    database: infect
    schema: rda_service_registry
    hosts:
        - host: ${SERVICE_REGISTRY_SERVICE_DB_HOST}
          username: ${SERVICE_REGISTRY_SERVICE_DB_USER}
          password: ${SERVICE_REGISTRY_SERVICE_DB_PASSWORD}
          port: 5432
          pools:
            - read
            - write
          maxConnections: 20


service-registry:
    host: http://l.dns.porn:9000


service-ttl: 10