server:
    port: 9000
    

database:
    type: postgres
    database: infect
    schema: rda_service_registry
    hosts:
        - host: ${SERVICE_REGISTRY_DB_HOST}
          username: root
          password: ${SERVICE_REGISTRY_DB_PASSWORD}
          port: 5432
          pools:
            - read
            - write
          maxConnections: 20
