server:
    port: 9000
    

database:
    type: postgres
    database: infect
    schema: rda_service_registry
    hosts:
        - host: 10.80.100.1
          username: postgres
          password: ${SERVICE_REGISTRY_DB_PASSWORD}
          port: 5432
          pools:
            - read
            - write
          maxConnections: 20


service-registry:
    host: http://l.dns.porn:9000


service-ttl: 10